blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/dm4t2/vue-currency-input/discussions/new?category=ideas
    about: Suggest any ideas you have using the discussion forums.
  - name: Help
    url: https://github.com/dm4t2/vue-currency-input/discussions/new?category=q-a
    about: If you have a question or need help, ask a question on the discussion forums.
